/*
linglong仓库

玲珑仓库接口

API version: 1.0.0
Contact: wurongjie@deepin.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiserver

import (
	"encoding/json"
)

// checks if the ResponseUploadTaskStatusInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseUploadTaskStatusInfo{}

// ResponseUploadTaskStatusInfo struct for ResponseUploadTaskStatusInfo
type ResponseUploadTaskStatusInfo struct {
	Status *string `json:"status,omitempty"`
}

// NewResponseUploadTaskStatusInfo instantiates a new ResponseUploadTaskStatusInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseUploadTaskStatusInfo() *ResponseUploadTaskStatusInfo {
	this := ResponseUploadTaskStatusInfo{}
	return &this
}

// NewResponseUploadTaskStatusInfoWithDefaults instantiates a new ResponseUploadTaskStatusInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseUploadTaskStatusInfoWithDefaults() *ResponseUploadTaskStatusInfo {
	this := ResponseUploadTaskStatusInfo{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseUploadTaskStatusInfo) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseUploadTaskStatusInfo) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseUploadTaskStatusInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ResponseUploadTaskStatusInfo) SetStatus(v string) {
	o.Status = &v
}

func (o ResponseUploadTaskStatusInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseUploadTaskStatusInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponseUploadTaskStatusInfo struct {
	value *ResponseUploadTaskStatusInfo
	isSet bool
}

func (v NullableResponseUploadTaskStatusInfo) Get() *ResponseUploadTaskStatusInfo {
	return v.value
}

func (v *NullableResponseUploadTaskStatusInfo) Set(val *ResponseUploadTaskStatusInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseUploadTaskStatusInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseUploadTaskStatusInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseUploadTaskStatusInfo(val *ResponseUploadTaskStatusInfo) *NullableResponseUploadTaskStatusInfo {
	return &NullableResponseUploadTaskStatusInfo{value: val, isSet: true}
}

func (v NullableResponseUploadTaskStatusInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseUploadTaskStatusInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


