/*
linglong仓库

玲珑仓库接口

API version: 1.0.0
Contact: wurongjie@deepin.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiserver

import (
	"encoding/json"
)

// checks if the Apiv2JSONError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Apiv2JSONError{}

// Apiv2JSONError struct for Apiv2JSONError
type Apiv2JSONError struct {
	Code *int32 `json:"code,omitempty"`
	Fields *map[string]string `json:"fields,omitempty"`
	Msg *string `json:"msg,omitempty"`
	TraceId *string `json:"trace_id,omitempty"`
}

// NewApiv2JSONError instantiates a new Apiv2JSONError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiv2JSONError() *Apiv2JSONError {
	this := Apiv2JSONError{}
	return &this
}

// NewApiv2JSONErrorWithDefaults instantiates a new Apiv2JSONError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiv2JSONErrorWithDefaults() *Apiv2JSONError {
	this := Apiv2JSONError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Apiv2JSONError) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Apiv2JSONError) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Apiv2JSONError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *Apiv2JSONError) SetCode(v int32) {
	o.Code = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *Apiv2JSONError) GetFields() map[string]string {
	if o == nil || IsNil(o.Fields) {
		var ret map[string]string
		return ret
	}
	return *o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Apiv2JSONError) GetFieldsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *Apiv2JSONError) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given map[string]string and assigns it to the Fields field.
func (o *Apiv2JSONError) SetFields(v map[string]string) {
	o.Fields = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *Apiv2JSONError) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Apiv2JSONError) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *Apiv2JSONError) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *Apiv2JSONError) SetMsg(v string) {
	o.Msg = &v
}

// GetTraceId returns the TraceId field value if set, zero value otherwise.
func (o *Apiv2JSONError) GetTraceId() string {
	if o == nil || IsNil(o.TraceId) {
		var ret string
		return ret
	}
	return *o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Apiv2JSONError) GetTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraceId) {
		return nil, false
	}
	return o.TraceId, true
}

// HasTraceId returns a boolean if a field has been set.
func (o *Apiv2JSONError) HasTraceId() bool {
	if o != nil && !IsNil(o.TraceId) {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given string and assigns it to the TraceId field.
func (o *Apiv2JSONError) SetTraceId(v string) {
	o.TraceId = &v
}

func (o Apiv2JSONError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Apiv2JSONError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.TraceId) {
		toSerialize["trace_id"] = o.TraceId
	}
	return toSerialize, nil
}

type NullableApiv2JSONError struct {
	value *Apiv2JSONError
	isSet bool
}

func (v NullableApiv2JSONError) Get() *Apiv2JSONError {
	return v.value
}

func (v *NullableApiv2JSONError) Set(val *Apiv2JSONError) {
	v.value = val
	v.isSet = true
}

func (v NullableApiv2JSONError) IsSet() bool {
	return v.isSet
}

func (v *NullableApiv2JSONError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiv2JSONError(val *Apiv2JSONError) *NullableApiv2JSONError {
	return &NullableApiv2JSONError{value: val, isSet: true}
}

func (v NullableApiv2JSONError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiv2JSONError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


