/*
linglong仓库

玲珑仓库接口

API version: 1.0.0
Contact: wurongjie@deepin.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiserver

import (
	"encoding/json"
)

// checks if the RequestFuzzySearchReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestFuzzySearchReq{}

// RequestFuzzySearchReq struct for RequestFuzzySearchReq
type RequestFuzzySearchReq struct {
	AppId *string `json:"appId,omitempty"`
	Arch *string `json:"arch,omitempty"`
	Channel *string `json:"channel,omitempty"`
	RepoName *string `json:"repoName,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewRequestFuzzySearchReq instantiates a new RequestFuzzySearchReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestFuzzySearchReq() *RequestFuzzySearchReq {
	this := RequestFuzzySearchReq{}
	return &this
}

// NewRequestFuzzySearchReqWithDefaults instantiates a new RequestFuzzySearchReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestFuzzySearchReqWithDefaults() *RequestFuzzySearchReq {
	this := RequestFuzzySearchReq{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *RequestFuzzySearchReq) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestFuzzySearchReq) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *RequestFuzzySearchReq) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *RequestFuzzySearchReq) SetAppId(v string) {
	o.AppId = &v
}

// GetArch returns the Arch field value if set, zero value otherwise.
func (o *RequestFuzzySearchReq) GetArch() string {
	if o == nil || IsNil(o.Arch) {
		var ret string
		return ret
	}
	return *o.Arch
}

// GetArchOk returns a tuple with the Arch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestFuzzySearchReq) GetArchOk() (*string, bool) {
	if o == nil || IsNil(o.Arch) {
		return nil, false
	}
	return o.Arch, true
}

// HasArch returns a boolean if a field has been set.
func (o *RequestFuzzySearchReq) HasArch() bool {
	if o != nil && !IsNil(o.Arch) {
		return true
	}

	return false
}

// SetArch gets a reference to the given string and assigns it to the Arch field.
func (o *RequestFuzzySearchReq) SetArch(v string) {
	o.Arch = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *RequestFuzzySearchReq) GetChannel() string {
	if o == nil || IsNil(o.Channel) {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestFuzzySearchReq) GetChannelOk() (*string, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *RequestFuzzySearchReq) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *RequestFuzzySearchReq) SetChannel(v string) {
	o.Channel = &v
}

// GetRepoName returns the RepoName field value if set, zero value otherwise.
func (o *RequestFuzzySearchReq) GetRepoName() string {
	if o == nil || IsNil(o.RepoName) {
		var ret string
		return ret
	}
	return *o.RepoName
}

// GetRepoNameOk returns a tuple with the RepoName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestFuzzySearchReq) GetRepoNameOk() (*string, bool) {
	if o == nil || IsNil(o.RepoName) {
		return nil, false
	}
	return o.RepoName, true
}

// HasRepoName returns a boolean if a field has been set.
func (o *RequestFuzzySearchReq) HasRepoName() bool {
	if o != nil && !IsNil(o.RepoName) {
		return true
	}

	return false
}

// SetRepoName gets a reference to the given string and assigns it to the RepoName field.
func (o *RequestFuzzySearchReq) SetRepoName(v string) {
	o.RepoName = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *RequestFuzzySearchReq) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestFuzzySearchReq) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *RequestFuzzySearchReq) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *RequestFuzzySearchReq) SetVersion(v string) {
	o.Version = &v
}

func (o RequestFuzzySearchReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestFuzzySearchReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.Arch) {
		toSerialize["arch"] = o.Arch
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.RepoName) {
		toSerialize["repoName"] = o.RepoName
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableRequestFuzzySearchReq struct {
	value *RequestFuzzySearchReq
	isSet bool
}

func (v NullableRequestFuzzySearchReq) Get() *RequestFuzzySearchReq {
	return v.value
}

func (v *NullableRequestFuzzySearchReq) Set(val *RequestFuzzySearchReq) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestFuzzySearchReq) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestFuzzySearchReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestFuzzySearchReq(val *RequestFuzzySearchReq) *NullableRequestFuzzySearchReq {
	return &NullableRequestFuzzySearchReq{value: val, isSet: true}
}

func (v NullableRequestFuzzySearchReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestFuzzySearchReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


