/*
linglong仓库

玲珑仓库接口

API version: 1.0.0
Contact: wurongjie@deepin.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiserver

import (
	"encoding/json"
)

// checks if the NewUploadTaskID200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewUploadTaskID200Response{}

// NewUploadTaskID200Response struct for NewUploadTaskID200Response
type NewUploadTaskID200Response struct {
	Code *int32 `json:"code,omitempty"`
	Data *ResponseNewUploadTaskResp `json:"data,omitempty"`
	Msg *string `json:"msg,omitempty"`
	TraceId *string `json:"trace_id,omitempty"`
}

// NewNewUploadTaskID200Response instantiates a new NewUploadTaskID200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewUploadTaskID200Response() *NewUploadTaskID200Response {
	this := NewUploadTaskID200Response{}
	return &this
}

// NewNewUploadTaskID200ResponseWithDefaults instantiates a new NewUploadTaskID200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewUploadTaskID200ResponseWithDefaults() *NewUploadTaskID200Response {
	this := NewUploadTaskID200Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *NewUploadTaskID200Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewUploadTaskID200Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *NewUploadTaskID200Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *NewUploadTaskID200Response) SetCode(v int32) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NewUploadTaskID200Response) GetData() ResponseNewUploadTaskResp {
	if o == nil || IsNil(o.Data) {
		var ret ResponseNewUploadTaskResp
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewUploadTaskID200Response) GetDataOk() (*ResponseNewUploadTaskResp, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NewUploadTaskID200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ResponseNewUploadTaskResp and assigns it to the Data field.
func (o *NewUploadTaskID200Response) SetData(v ResponseNewUploadTaskResp) {
	o.Data = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *NewUploadTaskID200Response) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewUploadTaskID200Response) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *NewUploadTaskID200Response) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *NewUploadTaskID200Response) SetMsg(v string) {
	o.Msg = &v
}

// GetTraceId returns the TraceId field value if set, zero value otherwise.
func (o *NewUploadTaskID200Response) GetTraceId() string {
	if o == nil || IsNil(o.TraceId) {
		var ret string
		return ret
	}
	return *o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewUploadTaskID200Response) GetTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraceId) {
		return nil, false
	}
	return o.TraceId, true
}

// HasTraceId returns a boolean if a field has been set.
func (o *NewUploadTaskID200Response) HasTraceId() bool {
	if o != nil && !IsNil(o.TraceId) {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given string and assigns it to the TraceId field.
func (o *NewUploadTaskID200Response) SetTraceId(v string) {
	o.TraceId = &v
}

func (o NewUploadTaskID200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewUploadTaskID200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.TraceId) {
		toSerialize["trace_id"] = o.TraceId
	}
	return toSerialize, nil
}

type NullableNewUploadTaskID200Response struct {
	value *NewUploadTaskID200Response
	isSet bool
}

func (v NullableNewUploadTaskID200Response) Get() *NewUploadTaskID200Response {
	return v.value
}

func (v *NullableNewUploadTaskID200Response) Set(val *NewUploadTaskID200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableNewUploadTaskID200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableNewUploadTaskID200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewUploadTaskID200Response(val *NewUploadTaskID200Response) *NullableNewUploadTaskID200Response {
	return &NullableNewUploadTaskID200Response{value: val, isSet: true}
}

func (v NullableNewUploadTaskID200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewUploadTaskID200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


