/*
linglong仓库

玲珑仓库接口

API version: 1.0.0
Contact: wurongjie@deepin.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiserver

import (
	"encoding/json"
)

// checks if the Apiv2SearchAppResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Apiv2SearchAppResponse{}

// Apiv2SearchAppResponse struct for Apiv2SearchAppResponse
type Apiv2SearchAppResponse struct {
	Code *int32 `json:"code,omitempty"`
	Data []RequestRegisterStruct `json:"data,omitempty"`
	TraceId *string `json:"trace_id,omitempty"`
}

// NewApiv2SearchAppResponse instantiates a new Apiv2SearchAppResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiv2SearchAppResponse() *Apiv2SearchAppResponse {
	this := Apiv2SearchAppResponse{}
	return &this
}

// NewApiv2SearchAppResponseWithDefaults instantiates a new Apiv2SearchAppResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiv2SearchAppResponseWithDefaults() *Apiv2SearchAppResponse {
	this := Apiv2SearchAppResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Apiv2SearchAppResponse) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Apiv2SearchAppResponse) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Apiv2SearchAppResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *Apiv2SearchAppResponse) SetCode(v int32) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Apiv2SearchAppResponse) GetData() []RequestRegisterStruct {
	if o == nil || IsNil(o.Data) {
		var ret []RequestRegisterStruct
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Apiv2SearchAppResponse) GetDataOk() ([]RequestRegisterStruct, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Apiv2SearchAppResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []RequestRegisterStruct and assigns it to the Data field.
func (o *Apiv2SearchAppResponse) SetData(v []RequestRegisterStruct) {
	o.Data = v
}

// GetTraceId returns the TraceId field value if set, zero value otherwise.
func (o *Apiv2SearchAppResponse) GetTraceId() string {
	if o == nil || IsNil(o.TraceId) {
		var ret string
		return ret
	}
	return *o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Apiv2SearchAppResponse) GetTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraceId) {
		return nil, false
	}
	return o.TraceId, true
}

// HasTraceId returns a boolean if a field has been set.
func (o *Apiv2SearchAppResponse) HasTraceId() bool {
	if o != nil && !IsNil(o.TraceId) {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given string and assigns it to the TraceId field.
func (o *Apiv2SearchAppResponse) SetTraceId(v string) {
	o.TraceId = &v
}

func (o Apiv2SearchAppResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Apiv2SearchAppResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.TraceId) {
		toSerialize["trace_id"] = o.TraceId
	}
	return toSerialize, nil
}

type NullableApiv2SearchAppResponse struct {
	value *Apiv2SearchAppResponse
	isSet bool
}

func (v NullableApiv2SearchAppResponse) Get() *Apiv2SearchAppResponse {
	return v.value
}

func (v *NullableApiv2SearchAppResponse) Set(val *Apiv2SearchAppResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiv2SearchAppResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiv2SearchAppResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiv2SearchAppResponse(val *Apiv2SearchAppResponse) *NullableApiv2SearchAppResponse {
	return &NullableApiv2SearchAppResponse{value: val, isSet: true}
}

func (v NullableApiv2SearchAppResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiv2SearchAppResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


