/*
linglong仓库

玲珑仓库接口

API version: 1.0.0
Contact: wurongjie@deepin.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiserver

import (
	"encoding/json"
)

// checks if the ResponseSignIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseSignIn{}

// ResponseSignIn struct for ResponseSignIn
type ResponseSignIn struct {
	Token *string `json:"token,omitempty"`
}

// NewResponseSignIn instantiates a new ResponseSignIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseSignIn() *ResponseSignIn {
	this := ResponseSignIn{}
	return &this
}

// NewResponseSignInWithDefaults instantiates a new ResponseSignIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseSignInWithDefaults() *ResponseSignIn {
	this := ResponseSignIn{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *ResponseSignIn) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSignIn) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *ResponseSignIn) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *ResponseSignIn) SetToken(v string) {
	o.Token = &v
}

func (o ResponseSignIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseSignIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableResponseSignIn struct {
	value *ResponseSignIn
	isSet bool
}

func (v NullableResponseSignIn) Get() *ResponseSignIn {
	return v.value
}

func (v *NullableResponseSignIn) Set(val *ResponseSignIn) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseSignIn) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseSignIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseSignIn(val *ResponseSignIn) *NullableResponseSignIn {
	return &NullableResponseSignIn{value: val, isSet: true}
}

func (v NullableResponseSignIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseSignIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


